<a href="https://colab.research.google.com/github/ravidmahajan/ai-ml-basics/blob/main/Intro_to_AI_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#INTRODUCTION TO NUMPY AND PANDAS
#numpy and pandas are crucial libraries used in python data science and machine learning
#below are examples for using DataFrames
#Pandas DataFrames are 2 dimensional data structures like lists except
#they can be used more flexibly to store data and display information

import pandas as pd

data = {
    "minutesWorked": [120, 40, 200],
    "jobType": ["lawyer","doctor","programmer"]
}
# print(data)

df = pd.DataFrame(data)
print(df)

   minutesWorked     jobType
0            120      lawyer
1             40      doctor
2            200  programmer

In [ ]:
#return a given row using loc
print(df.loc[[0]]) #loc also takes lists that contain indexes of rows
print("============================")
print(df.loc[[1,2]])
print("============================")
print(df.loc[[0,2]])
#loc also works by using the name of the specified index

   minutesWorked jobType
0            120  lawyer
============================
   minutesWorked     jobType
1             40      doctor
2            200  programmer
============================
   minutesWorked     jobType
0            120      lawyer
2            200  programmer

In [ ]:
#dataframes are built with an index parameter that you can modify
df = pd.DataFrame(data, index = ["Monday","Tuesday","Wednesday"])

df.head() #head(n) displays n number of rows to the user (defaults to 5)

           minutesWorked     jobType
Monday               120      lawyer
Tuesday               40      doctor
Wednesday            200  programmer

In [18]:
#How these dataframes are used practically? CSV files
df = pd.read_csv('/content/sample_data/diabetes.csv') #also can use read_table()
df.head()
#df.to_string() prints raw dataframe

#lets get some info
# print(df.shape[1]) #how many columns
# print(df.shape[0]) #how many rows

#doing processes
# df['BMI'] = df.index #adding column based on index counter
# df.head()

df.drop('SkinThickness', axis=1, inplace=True)
#drop('colName', axis=0 for rows 1 for cols, inplace is so the dataframe is reassigning itself)
df.head()

#re

,Pregnancies,Glucose,BloodPressure,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,0,33.6,0.627,50,1
1,1,85,66,0,26.6,0.351,31,0
2,8,183,64,0,23.3,0.672,32,1
3,1,89,66,94,28.1,0.167,21,0
4,0,137,40,168,43.1,2.288,33,1

In [19]:
# numpy functions with given data
data = {
    "Item": ["Banana", "Milk", "Eggs", "Yogurt", "Chips", "Beans", "Tortillas", "Pineapple", "Dip", "Onion", "Garlic", "Tomatoes", "Eggplant", "Fish", "Potatoes", "Okra", "Soy", "Rice" , "Peppers"],
    "Quantity": [1200, 182, 139, 235, 301, 86, 25, 3456, 234, 5678, 123 , 95, 1234, 1234, 6357 , 95, 9687, 967, 43],
    "Cost": [5, 4, 12, 29, 10, 12, 3, 5, 6, 1, 7, 2, 9, 18, 25, 12, 5, 19, 20]
}

df = pd.DataFrame(data)

# # average of COLUMNS
# df.mean(numeric_only=True)
# # df.mean(axis=0)

# # average of ROWS (meaningless in our case)
# # df.mean(axis=1)

# # # sum of COLUMNS
# df.sum(numeric_only=True)

# # # sum specific column
# df["Cost"].sum()

# method to get summary statistics
def get_statistics(df):
    numeric_columns = df.select_dtypes(include=['number'])
    for column in numeric_columns:
        mean = df[column].mean()
        median = df[column].median()
        mode = df[column].mode()
        print(f"{column.capitalize()} Stats:")
        print(f"Mean: {mean}")
        print(f"Median: {median}")
        print(f"Mode: {mode}\n")

get_statistics(df)

# # can also use describe() method
df.describe()

Quantity Stats:
Mean: 1651.1052631578948
Median: 235.0
Mode: 0      95
1    1234
Name: Quantity, dtype: int64

Cost Stats:
Mean: 10.736842105263158
Median: 9.0
Mode: 0     5
1    12
Name: Cost, dtype: int64

          Quantity       Cost
count    19.000000  19.000000
mean   1651.105263  10.736842
std    2711.630217   8.040468
min      25.000000   1.000000
25%     109.000000   5.000000
50%     235.000000   9.000000
75%    1234.000000  15.000000
max    9687.000000  29.000000

# Your Turn
Using the dataframe in the section below that has the **name**, **age**, and **occupation** of a person, do the following actions and print/display/show the results:
1. Display the first 5 rows of the dataframe
2. Add a new row with the values "Rosa", "24", "Boxer"
3. Add a column titled "Adult." The values should be 1 if the person is greater than or equal to 18 and 0 if less than 18
4. Drop the "Age" column
5. Find the summary statistics of the age column, then use describe to check your results

In [21]:
import pandas as pd

data = {
    "Name": ["Amy", "Joseph", "Rebecca", "Karl", "Tommy", "Alex"],
    "Age": [12, 18, 19, 25, 30, 8],
    "Occupation": ["sailor", "lawyer", "doctor", "firefighter", "actor", "youtuber"]
}

df_people = pd.DataFrame(data)
print("Initial DataFrame:")
display(df_people.head())

Initial DataFrame:

      Name  Age   Occupation
0      Amy   12       sailor
1   Joseph   18       lawyer
2  Rebecca   19       doctor
3     Karl   25  firefighter
4    Tommy   30        actor

In [22]:
# 2. Add a new row with the values "Rosa", "24", "Boxer"
new_row = pd.DataFrame([{"Name": "Rosa", "Age": 24, "Occupation": "Boxer"}])
df_people = pd.concat([df_people, new_row], ignore_index=True)
print("\nDataFrame after adding a new row:")
display(df_people)

DataFrame after adding a new row:

      Name  Age   Occupation
0      Amy   12       sailor
1   Joseph   18       lawyer
2  Rebecca   19       doctor
3     Karl   25  firefighter
4    Tommy   30        actor
5     Alex    8     youtuber
6     Rosa   24        Boxer

In [23]:
# 3. Add a column titled "Adult." The values should be 1 if the person is greater than or equal to 18 and 0 if less than 18
df_people['Adult'] = df_people['Age'].apply(lambda x: 1 if x >= 18 else 0)
print("\nDataFrame after adding 'Adult' column:")
display(df_people)

DataFrame after adding 'Adult' column:

      Name  Age   Occupation  Adult
0      Amy   12       sailor      0
1   Joseph   18       lawyer      1
2  Rebecca   19       doctor      1
3     Karl   25  firefighter      1
4    Tommy   30        actor      1
5     Alex    8     youtuber      0
6     Rosa   24        Boxer      1

In [24]:
# 5. Find the summary statistics of the age column, then use describe to check your results
print("\nSummary statistics for 'Age' column:")
display(df_people['Age'].describe())

Summary statistics for 'Age' column:

count     7.000000
mean     19.428571
std       7.656308
min       8.000000
25%      15.000000
50%      19.000000
75%      24.500000
max      30.000000
Name: Age, dtype: float64

In [25]:
# 4. Drop the "Age" column
df_people = df_people.drop(columns=['Age'])
print("\nDataFrame after dropping 'Age' column:")
display(df_people)

DataFrame after dropping 'Age' column:

      Name   Occupation  Adult
0      Amy       sailor      0
1   Joseph       lawyer      1
2  Rebecca       doctor      1
3     Karl  firefighter      1
4    Tommy        actor      1
5     Alex     youtuber      0
6     Rosa        Boxer      1